In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [3]:
## 1D Array
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5) # 1-row and 5-columns
print(arr2)

[[1 2 3 4 5]]


In [4]:
## 2D Array
arr3 = np.array([[1,2,3,4,5],[2,3,5,6,7]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 5 6 7]]
(2, 5)


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
## Identity Matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition: ", arr1 + arr2)

Addition:  [11 22 33 44 55]


In [9]:
## Universal Functions
arr = np.array([1,2,3,4,5])

## Square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

# Sin
print(np.sin(arr))

#log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [10]:
## Array slicing and indexing

arry = np.array([[1,2,3,5],[6,7,8,9],[4,7,9,10]])
print("Array: \n", arry)

print(arry[0][1])

print(arry[1:,2:])

print(arry[0:2,2:])

print(arry[1:,1:3])

Array: 
 [[ 1  2  3  5]
 [ 6  7  8  9]
 [ 4  7  9 10]]
2
[[ 8  9]
 [ 9 10]]
[[3 5]
 [8 9]]
[[7 8]
 [7 9]]


In [11]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(data > 5)

data1 = data[data >5]
print(data1)

data2 = data[(data >5) & (data<8)]
print(data2)

[False False False False False  True  True  True  True  True  True  True]
[ 6  7  8  9 10 11 12]
[6 7]


In [12]:
import pandas as pd

In [13]:
## Series

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [14]:
## Series from dictorionary

data = {"a":1,"b":2,"c":3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [15]:
data = {
    "Name":["John","Jack","Jill"],
    "Age":[12,23,34],
    "City":["New York","Little Rock","Paris"]
}

df = pd.DataFrame(data)

In [16]:
df

Name  Age         City
0  John   12     New York
1  Jack   23  Little Rock
2  Jill   34        Paris

In [17]:
print(df['Name'])
print(df.loc[0])

0    John
1    Jack
2    Jill
Name: Name, dtype: object
Name        John
Age           12
City    New York
Name: 0, dtype: object


In [18]:
df.iloc[0][2]

/var/folders/07/8j6bcwpn5_qfb0_tjmt2qg100000gn/T/ipykernel_1745/2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]


'New York'

In [19]:
print(df.at[1,'City'])

Little Rock


In [20]:
print(df.iat[1,2])

Little Rock


In [21]:
## Adding column in DF

df['Salary'] = [1222,3424,3242]

df

Name  Age         City  Salary
0  John   12     New York    1222
1  Jack   23  Little Rock    3424
2  Jill   34        Paris    3242

In [22]:
## Drop a column

df.drop('Salary', axis=1,inplace=True) ## inplace make the operation permanent, similar to assign it to df = df.drop('Salary',axis=1)


In [23]:
## Add age to the column

df['Age'] = df['Age'] + 1
df

Name  Age         City
0  John   13     New York
1  Jack   24  Little Rock
2  Jill   35        Paris

In [24]:
from common_codes.utils import Utils
df = pd.read_csv(Utils.get_file_path('data.csv'))
df.head(5)

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [25]:

df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [26]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [27]:
## Handling missing values
df.isnull().any()
df.isnull().sum()


Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [28]:
## Filling missing values with 0
df_filled = df.fillna(0)

df_filled.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [29]:
## Filling missing values with mean of that column
df['Sales_filledNA'] = df['Sales'].fillna(df['Sales'].mean())
df.head(5)

Date Category  Value   Product  Sales Region  Sales_filledNA
0  2023-01-01        A   28.0  Product1  754.0   East           754.0
1  2023-01-02        B   39.0  Product3  110.0  North           110.0
2  2023-01-03        C   32.0  Product2  398.0   East           398.0
3  2023-01-04        B    8.0  Product1  522.0   East           522.0
4  2023-01-05        B   26.0  Product3  869.0  North           869.0

In [30]:
## Renaming the column

df = df.rename(columns={'Date':'Sale Data'})
df.head()

Sale Data Category  Value   Product  Sales Region  Sales_filledNA
0  2023-01-01        A   28.0  Product1  754.0   East           754.0
1  2023-01-02        B   39.0  Product3  110.0  North           110.0
2  2023-01-03        C   32.0  Product2  398.0   East           398.0
3  2023-01-04        B    8.0  Product1  522.0   East           522.0
4  2023-01-05        B   26.0  Product3  869.0  North           869.0

In [31]:
df['Value_New'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

Sale Data Category  Value   Product  Sales Region  Sales_filledNA  \
0  2023-01-01        A   28.0  Product1  754.0   East           754.0   
1  2023-01-02        B   39.0  Product3  110.0  North           110.0   
2  2023-01-03        C   32.0  Product2  398.0   East           398.0   
3  2023-01-04        B    8.0  Product1  522.0   East           522.0   
4  2023-01-05        B   26.0  Product3  869.0  North           869.0   

   Value_New  
0         28  
1         39  
2         32  
3          8  
4         26

In [32]:
df['New_Value'] = df['Value'].apply(lambda x:x*2)
df.head()

Sale Data Category  Value   Product  Sales Region  Sales_filledNA  \
0  2023-01-01        A   28.0  Product1  754.0   East           754.0   
1  2023-01-02        B   39.0  Product3  110.0  North           110.0   
2  2023-01-03        C   32.0  Product2  398.0   East           398.0   
3  2023-01-04        B    8.0  Product1  522.0   East           522.0   
4  2023-01-05        B   26.0  Product3  869.0  North           869.0   

   Value_New  New_Value  
0         28       56.0  
1         39       78.0  
2         32       64.0  
3          8       16.0  
4         26       52.0

In [36]:
## Data Aggregation and Grouping

grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)


grouped_sum = df.groupby(['Product', 'Region'])['Sales'].sum()
print(grouped_sum)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64
Product   Region
Product1  East      4205.0
          North     1737.0
          South     1346.0
          West      1335.0
Product2  East       856.0
          North      843.0
          South     2240.0
          West      3435.0
Product3  East      1956.0
          North     3428.0
          South     1572.0
          West      2675.0
Name: Sales, dtype: float64


In [40]:
## Aggregate multiple functions

grouped_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean     sum  count
Region                          
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17


In [44]:
## Merging a Datframe

df1 = pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'], 'Value2':[1,2,4]})


In [45]:
pd.merge(df1,df2,on='Key',how='inner')

Key  Value1  Value2
0   A       1       1
1   B       2       2

In [46]:
pd.merge(df1,df2,on='Key',how='outer')

Key  Value1  Value2
0   A     1.0     1.0
1   B     2.0     2.0
2   C     3.0     NaN
3   D     NaN     4.0

In [47]:
pd.merge(df1,df2,on='Key',how='left')

Key  Value1  Value2
0   A       1     1.0
1   B       2     2.0
2   C       3     NaN

In [48]:
pd.merge(df1,df2,on='Key',how='right')

Key  Value1  Value2
0   A     1.0       1
1   B     2.0       2
2   D     NaN       4